### PR TITLE
pin torchani to 2.2.2

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by peastman — APPROVED** [review]
Looks good.

**Comment by peastman** [comment]
Though actually, I wonder if we want to make it `>2.2.2`?  For the environment file it's good to pin to a particular version, but an exact pin in the package will make it impossible to install later versions.  We just need a version that is late enough to include the bug fix.

**Comment by peastman** [comment]
Sorry, I meant to say `>=2.2.2`.

**Comment by mikemhenry** [comment]
Yes I agree! I didn't check to see if they had a newer version or not, so I was playing it safe, but I don't think we have any reason to believe (until it happens) that a newer version will be problematic. 

> but an exact pin in the package will make it impossible to install later versions

Yes that can get really tricky to deal with.

**Pull request merged**
