### PR TITLE
don't pull in nnpops on osx or windows

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
> * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

Well that answers my question!

**Comment by mikemhenry** [comment]
Looks like 3.10 if failing for OSX and Linux because we don't have 3.10 builds for openmm, which is fine, so I will go ahead and merge this in.

**Comment by peastman** [comment]
The 8.0 beta does have 3.10 builds.  I think we need a proper beta release of this package that is built against the betas of OpenMM and OpenMM-Torch.  This also seems to have only built for x86, not ARM.

**Comment by mikemhenry** [comment]
@peastman This package used to be `noarch` so I forgot to add the arm builds! I will fix that!

Also I misread the error:
`package openmm-torch-0.03-py36h110734a_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed`

It looks like openmm-torch is missing the python 3.10 builds with the `main` tag, but has them with the `openmm_rc` tag, so I will need to also rebuild this package where it pulls those in.

**Pull request merged**
